apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agents
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: vox
  source:
    repoURL: https://github.com/DuyThong2/voxenta-helm.git
    targetRevision: main
    path: charts/agents
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: vox-agents
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

